name: Internal - Common Continuous Integration tasks

on:
  workflow_call:

jobs:
  linter:
    uses: hoverkraft-tech/ci-github-common/.github/workflows/linter.yml@0.7.3

  test-action-get-package-manager:
    name: Test action "get-package-manager"
    needs: linter
    uses: ./.github/workflows/__test-action-get-package-manager.yml

  test-action-has-installed-dependencies:
    name: Test action "has-installed-dependencies"
    needs: linter
    uses: ./.github/workflows/__test-action-has-installed-dependencies.yml

  test-action-setup-node:
    name: Test action "setup-node"
    needs: linter
    uses: ./.github/workflows/__test-action-setup-node.yml

  test-workflow-continuous-integration:
    name: Test workflow "continuous-integration"
    needs: linter
    uses: ./.github/workflows/__test-workflow-continuous-integration.yml
