name: Internal - Test Continuous integration workflow

on:
  workflow_call:

jobs:
  tests:
    uses: ./.github/workflows/continuous-integration.yml
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}