name: Internal - Test Continuous integration workflow

on:
  workflow_call:

permissions:
  contents: read
  security-events: write
  # FIXME: This is a workaround for having workflow ref. See https://github.com/orgs/community/discussions/38659
  id-token: write

jobs:
  act:
    name: Act - Run the continuous integration workflow
    uses: ./.github/workflows/continuous-integration.yml
    with:
      build: |
        {
          "artifact": "dist"
        }

  assert:
    name: Assert - Ensure build artifact has been uploaded
    runs-on: ubuntu-latest
    needs: act
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: "/"

      - name: Check the build artifacts
        run: test -f dist/test.txt
