# NodeJS Continuous Integration
# ==========================
# Workflow to performs continuous integration steps agains a NodeJs project:
# - CodeQL analysis
# - Linting
# - Build
# - Test

name: NodeJS Continuous Integration

on:
  workflow_call:
    inputs:
      build:
        description: Build parameters. Must be a string or a json object.
        type: string
        required: false
        default: "build"
      checks:
        description: "Optional flag to enable check steps."
        type: boolean
        required: false
        default: true
      lint:
        description: "Optional flag to enable linting"
        type: boolean
        required: false
        default: true
      code-ql:
        description: "Code QL analysis language. See https://github.com/github/codeql-action"
        type: string
        required: false
        default: "typescript"
      test:
        description: "Optional flag to enable test."
        type: boolean
        required: false
        default: true
      coverage:
        description: "Specifify code coverage reporter. Supported values: 'codecov'"
        type: string
        required: false
        default: "codecov"
    secrets:
      codecov-token:
        description: "Codecov token. See [https://github.com/codecov/codecov-action](https://github.com/codecov/codecov-action)"
        required: false

jobs:
  code-ql:
    name: 🛡️ CodeQL Analysis
    if: inputs.checks == true && inputs.code-ql != ''
    permissions:
      security-events: write
    runs-on: "ubuntu-latest"
    steps:
      - uses: hoverkraft-tech/ci-github-common/actions/checkout@0.12.1
      - uses: github/codeql-action/init@v3.24.9
        with:
          languages: ${{ inputs.code-ql }}
      - uses: github/codeql-action/analyze@v3.24.9

  setup:
    name: ⚙️ Setup
    runs-on: "ubuntu-latest"
    # FIXME: This is a workaround for having workflow ref. See https://github.com/orgs/community/discussions/38659
    permissions:
      contents: read
      id-token: write
    outputs:
      build-commands: ${{ steps.build-variables.outputs.commands }}
      build-artifact: ${{ steps.build-variables.outputs.artifact }}
    steps:
      # FIXME: This is a workaround for having workflow ref. See https://github.com/orgs/community/discussions/38659
      # jscpd:ignore-start
      - uses: hoverkraft-tech/ci-github-common/actions/checkout@0.12.1

      - id: oidc
        uses: ChristopherHX/oidc@v3
      - uses: actions/checkout@v4 # checks out called workflow
        with:
          path: ./self-workflow
          repository: ${{ steps.oidc.outputs.job_workflow_repo_name_and_owner }}
          ref: ${{ steps.oidc.outputs.job_workflow_repo_ref }}
      # jscpd:ignore-end

      - id: setup-node
        uses: ./self-workflow/actions/setup-node

      - id: build-variables
        if: inputs.build != ''
        uses: actions/github-script@v7
        with:
          script: |
            const buildInput = `${{ inputs.build }}`.trim();

            let commands = [];

            // Build input can be json or string
            try {
              const build = JSON.parse(buildInput);
              if (Array.isArray(build)) {
                commands = build;
              } else {
                commands = build.commands ?? ["build"];

                if (build.artifact) {
                  if(typeof build.artifact === 'string') {
                    build.artifact = build.artifact.trim().split('\n');
                  }
                  const sanitizedArtifacts = build.artifact
                    .map(artifact => artifact.trim())
                    .filter(Boolean)
                    .map(artifact => {
                      if(!artifact.includes('*')) {
                        return artifact;
                      }

                      // FIXME: Workaround to preserve full path to artifact
                      // Add a wildcard to the first folder of the path
                      const workspace = `${{ github.workspace }}`.replace(/\/([^/]+)/, '/*$1');
                      return `${workspace}/${artifact}`;
                    });

                  core.setOutput('artifact', sanitizedArtifacts.join('\n'));
                }
              }
            } catch (e) {
              commands = buildInput.split('\n');
            }

            const sanitizedCommands = commands.map(command => command.trim()).filter(Boolean);
            if(!sanitizedCommands.length) {
              core.setFailed('No build commands found');
            }

            core.setOutput('commands', sanitizedCommands.join('\n'));

  lint:
    name: 👕 Lint
    if: inputs.checks == true && inputs.lint != false
    runs-on: "ubuntu-latest"
    needs: setup
    # jscpd:ignore-start
    # FIXME: This is a workaround for having workflow ref. See https://github.com/orgs/community/discussions/38659
    permissions:
      contents: read
      id-token: write
    steps:
      # FIXME: This is a workaround for having workflow ref. See https://github.com/orgs/community/discussions/38659
      - uses: hoverkraft-tech/ci-github-common/actions/checkout@0.12.1

      - id: oidc
        uses: ChristopherHX/oidc@v3
      - uses: actions/checkout@v4 # checks out called workflow
        with:
          path: ./self-workflow
          repository: ${{ steps.oidc.outputs.job_workflow_repo_name_and_owner }}
          ref: ${{ steps.oidc.outputs.job_workflow_repo_ref }}
      # jscpd:ignore-end

      - id: setup-node
        uses: ./self-workflow/actions/setup-node
        with:
          dependencies-cache: |
            nx
            prettier

      - run: ${{ steps.setup-node.outputs.run-script-command }} lint
        env:
          NX_REJECT_UNKNOWN_LOCAL_CACHE: "0"

  build:
    name: 🏗️ Build
    if: inputs.checks == true && needs.setup.outputs.build-commands
    runs-on: "ubuntu-latest"
    needs: setup
    # jscpd:ignore-start
    # FIXME: This is a workaround for having workflow ref. See https://github.com/orgs/community/discussions/38659
    permissions:
      contents: read
      id-token: write
    steps:
      # FIXME: This is a workaround for having workflow ref. See https://github.com/orgs/community/discussions/38659
      - uses: hoverkraft-tech/ci-github-common/actions/checkout@0.12.1

      - id: oidc
        uses: ChristopherHX/oidc@v3
      - uses: actions/checkout@v4 # checks out called workflow
        with:
          path: ./self-workflow
          repository: ${{ steps.oidc.outputs.job_workflow_repo_name_and_owner }}
          ref: ${{ steps.oidc.outputs.job_workflow_repo_ref }}
      # jscpd:ignore-end

      - id: setup-node
        uses: ./self-workflow/actions/setup-node
        with:
          dependencies-cache: |
            nx
            gatsby
            storybook

      - run: |
          BUILD_COMMANDS="${{ needs.setup.outputs.build-commands }}"

          echo "$BUILD_COMMANDS" | while IFS= read -r COMMAND ; do
              # Trim whitespace
              COMMAND=$(echo "$COMMAND" | xargs)

              # Skip empty lines
              if [ -z "$COMMAND" ]; then
                  continue
              fi

              echo -e "\n - Running $COMMAND"
              ${{ steps.setup-node.outputs.run-script-command }} "$COMMAND"
          done
        env:
          NX_REJECT_UNKNOWN_LOCAL_CACHE: "0"

      - if: needs.setup.outputs.build-artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ${{ needs.setup.outputs.build-artifact }}

  test:
    name: 🧪 Test
    if: inputs.checks == true && inputs.test == true
    runs-on: "ubuntu-latest"
    needs:
      - setup
      - build
    # FIXME: This is a workaround for having workflow ref. See https://github.com/orgs/community/discussions/38659
    permissions:
      contents: read
      id-token: write
    steps:
      # FIXME: This is a workaround for having workflow ref. See https://github.com/orgs/community/discussions/38659
      - uses: hoverkraft-tech/ci-github-common/actions/checkout@0.12.1

      - if: needs.setup.outputs.build-artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: "/"

      - id: oidc
        uses: ChristopherHX/oidc@v3
      - uses: actions/checkout@v4 # checks out called workflow
        with:
          path: ./self-workflow
          repository: ${{ steps.oidc.outputs.job_workflow_repo_name_and_owner }}
          ref: ${{ steps.oidc.outputs.job_workflow_repo_ref }}

      - id: setup-node
        uses: ./self-workflow/actions/setup-node
        with:
          dependencies-cache: |
            nx
            jest

      - run: ${{ steps.setup-node.outputs.run-script-command }} test:ci
        env:
          CI: "true"
          NX_REJECT_UNKNOWN_LOCAL_CACHE: "0"

      - name: 📊 Code coverage
        if: inputs.coverage == 'codecov'
        uses: codecov/codecov-action@v4.1.1
        with:
          token: ${{ secrets.codecov-token }}
